import * as React from "react"
import Svg, { SvgProps, Rect } from "react-native-svg"
const SvgComponent = (props: SvgProps) => (
  <Svg
    xmlns="http://www.w3.org/2000/svg"
    className="ionicon"
    viewBox="0 0 512 512"
    {...props}
  >
    <Rect
      width={176}
      height={176}
      x={48}
      y={48}
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={32}
      rx={20}
      ry={20}
    />
    <Rect
      width={176}
      height={176}
      x={288}
      y={48}
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={32}
      rx={20}
      ry={20}
    />
    <Rect
      width={176}
      height={176}
      x={48}
      y={288}
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={32}
      rx={20}
      ry={20}
    />
    <Rect
      width={176}
      height={176}
      x={288}
      y={288}
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={32}
      rx={20}
      ry={20}
    />
  </Svg>
)
export default SvgComponent
